apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-fault
spec:
  selector:
    matchLabels:
      app: paymentservice-fault
  template:
    metadata:
      labels:
        app: paymentservice-fault
    spec:
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/paymentservice:v0.10.1
        resources:
          requests:
            cpu: 100m
            memory: 6Mi
          limits:
            cpu: 200m
            memory: 8Mi # Slightly higher to bypass docker minimum, but still likely to OOM
